// examples/svelte/src/App.svelte
<script>
import heroImg from './assets/hero.png';
import svelteLogo from './assets/svelte.svg';
import viteLogo from './assets/vite.svg';
import Counter from './lib/Counter.svelte';
</script>

<section id="center">
  <div class="hero">
    <img src={heroImg} class="base" width="170" height="179" alt="" />
    <img src={svelteLogo} class="framework" alt="Svelte logo" />
    <img src={viteLogo} class="vite" alt="Vite logo" />
  </div>
  <div>
    <h1>Get started</h1>
    <p>Edit <code>src/App.svelte</code> and save to test <code>HMR</code></p>
  </div>
  <Counter />
</section>

<div class="ticks"></div>

<section id="next-steps">
  <div id="docs">
    <svg class="icon" role="presentation" aria-hidden="true">
      <use href={`${import.meta.env.BASE_URL}icons.svg#documentation-icon`}
      ></use>
    </svg>
    <h2>Documentation</h2>
    <p>Your questions, answered</p>
    <ul>
      <li>
        <a href="https://vite.dev/" target="_blank" rel="noreferrer">
          <img class="logo" src={viteLogo} alt="" />
          Explore Vite
        </a>
      </li>
      <li>
        <a href="https://svelte.dev/" target="_blank" rel="noreferrer">
          <img class="button-icon" src={svelteLogo} alt="" />
          Learn more
        </a>
      </li>
    </ul>
  </div>
  <div id="social">
    <svg class="icon" role="presentation" aria-hidden="true">
      <use href={`${import.meta.env.BASE_URL}icons.svg#social-icon`}></use>
    </svg>
    <h2>Connect with us</h2>
    <p>Join the Vite community</p>
    <ul>
      <li>
        <a
          href="https://github.com/vitejs/vite"
          target="_blank"
          rel="noreferrer"
        >
          <svg class="button-icon" role="presentation" aria-hidden="true">
            <use href={`${import.meta.env.BASE_URL}icons.svg#github-icon`}
            ></use>
          </svg>
          GitHub
        </a>
      </li>
      <li>
        <a href="https://chat.vite.dev/" target="_blank" rel="noreferrer">
          <svg class="button-icon" role="presentation" aria-hidden="true">
            <use href={`${import.meta.env.BASE_URL}icons.svg#discord-icon`}
            ></use>
          </svg>
          Discord
        </a>
      </li>
      <li>
        <a href="https://x.com/vite_js" target="_blank" rel="noreferrer">
          <svg class="button-icon" role="presentation" aria-hidden="true">
            <use href={`${import.meta.env.BASE_URL}icons.svg#x-icon`}></use>
          </svg>
          X.com
        </a>
      </li>
      <li>
        <a
          href="https://bsky.app/profile/vite.dev"
          target="_blank"
          rel="noreferrer"
        >
          <svg class="button-icon" role="presentation" aria-hidden="true">
            <use href={`${import.meta.env.BASE_URL}icons.svg#bluesky-icon`}
            ></use>
          </svg>
          Bluesky
        </a>
      </li>
    </ul>
  </div>
</section>

<div class="ticks"></div>
<section id="spacer"></section>

// examples/react/src/App.tsx
import './App.css';

import { useState } from 'react';
import heroImg from './assets/hero.png';
import reactLogo from './assets/react.svg';
import viteLogo from './assets/vite.svg';

function App() {
  const [count, setCount] = useState(0);

  return (
    <>
      <section id="center">
        <div className="hero">
          <img src={heroImg} className="base" width="170" height="179" alt="" />
          <img src={reactLogo} className="framework" alt="React logo" />
          <img src={viteLogo} className="vite" alt="Vite logo" />
        </div>
        <div>
          <h1>Get started</h1>
          <p>
            Edit <code>src/App.tsx</code> and save to test <code>HMR</code>
          </p>
        </div>
        <button type="button" className="counter" onClick={() => setCount((count) => count + 1)}>
          Count is {count}
        </button>
      </section>

      <div className="ticks" />

      <section id="next-steps">
        <div id="docs">
          <svg className="icon" role="presentation" aria-hidden="true">
            <use href={`${import.meta.env.BASE_URL}icons.svg#documentation-icon`} />
          </svg>
          <h2>Documentation</h2>
          <p>Your questions, answered</p>
          <ul>
            <li>
              <a href="https://vite.dev/" target="_blank" rel="noreferrer noopener">
                <img className="logo" src={viteLogo} alt="" />
                Explore Vite
              </a>
            </li>
            <li>
              <a href="https://react.dev/" target="_blank" rel="noreferrer noopener">
                <img className="button-icon" src={reactLogo} alt="" />
                Learn more
              </a>
            </li>
          </ul>
        </div>
        <div id="social">
          <svg className="icon" role="presentation" aria-hidden="true">
            <use href={`${import.meta.env.BASE_URL}icons.svg#social-icon`} />
          </svg>
          <h2>Connect with us</h2>
          <p>Join the Vite community</p>
          <ul>
            <li>
              <a href="https://github.com/vitejs/vite" target="_blank" rel="noreferrer noopener">
                <svg className="button-icon" role="presentation" aria-hidden="true">
                  <use href={`${import.meta.env.BASE_URL}icons.svg#github-icon`} />
                </svg>
                GitHub
              </a>
            </li>
            <li>
              <a href="https://chat.vite.dev/" target="_blank" rel="noreferrer noopener">
                <svg className="button-icon" role="presentation" aria-hidden="true">
                  <use href={`${import.meta.env.BASE_URL}icons.svg#discord-icon`} />
                </svg>
                Discord
              </a>
            </li>
            <li>
              <a href="https://x.com/vite_js" target="_blank" rel="noreferrer noopener">
                <svg className="button-icon" role="presentation" aria-hidden="true">
                  <use href={`${import.meta.env.BASE_URL}icons.svg#x-icon`} />
                </svg>
                X.com
              </a>
            </li>
            <li>
              <a href="https://bsky.app/profile/vite.dev" target="_blank" rel="noreferrer noopener">
                <svg className="button-icon" role="presentation" aria-hidden="true">
                  <use href={`${import.meta.env.BASE_URL}icons.svg#bluesky-icon`} />
                </svg>
                Bluesky
              </a>
            </li>
          </ul>
        </div>
      </section>

      <div className="ticks" />
      <section id="spacer" />
    </>
  );
}

export default App;
